prompt --application/shared_components/email/templates/form_received
begin
--   Manifest
--     EMAIL TEMPLATE: Form Received
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2026.03.30'
,p_release=>'26.1.1'
,p_default_workspace_id=>13144316281138660209
,p_default_application_id=>125939
,p_default_id_offset=>14279541879556441716
,p_default_owner=>'WKSP_MANUELPORTOFOLIO'
);
wwv_flow_imp_shared.create_email_template(
 p_id=>wwv_flow_imp.id(14345142470302266107)
,p_name=>'Form Received'
,p_static_id=>'FORM_RECEIVED'
,p_version_number=>2
,p_subject=>'New Report Received - #REPORT_NUMBER#'
,p_html_body=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<body style="margin:0;padding:0;background-color:#f4f6f9;font-family:Arial,Helvetica,sans-serif;">',
'',
'  <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f6f9;">',
'    <tr>',
'      <td align="center" style="padding:30px 0;">',
'',
'        <!-- Container -->',
'        <table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:6px;overflow:hidden;border:1px solid #dddddd;">',
'',
'          <!-- Solid color header (compatible with all email clients) -->',
'          <tr>',
'            <td style="background-color:#134e4a; color:#ffffff; text-align:center; padding:24px;">',
'              <!-- Solid background color as a fallback -->',
'              <!-- Gradient effect using nested tables for supporting email clients -->',
'              <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#134e4a; border-radius:6px;">',
'                <tr>',
'                  <td style="background-color:#0d9488; padding:4px 0;">',
unistr('                    <h1 style="margin:0;font-size:22px; color:#ffffff;">\D83D\DCCB New WBS Report</h1>'),
'                    <p style="margin:6px 0 0;font-size:14px; color:#ccfbf1;">',
'                      Report Number: <strong style="color:#ffffff;">#REPORT_NUMBER#</strong>',
'                    </p>',
'                  </td>',
'                </tr>',
'              </table>',
'             </td>',
'           </tr>',
'',
'          <!-- Body -->',
'          <tr>',
'            <td style="padding:30px;color:#333333;font-size:14px;line-height:1.6;">',
'',
'              <p style="margin-top:0;">',
'                Dear <strong>WBS Investigation Team</strong>,',
'              </p>',
'',
'              <p>',
'                A <strong>NEW</strong> report has been received through the WBS system and requires',
'                further handling in accordance with the applicable procedures.',
'              </p>',
'',
'              <!-- Summary Table -->',
'              <table width="100%" cellpadding="8" cellspacing="0" style="margin:20px 0; background:#f8fafc; border-radius:8px; border:1px solid #e2e8f0;">',
'                <tr style="border-bottom:1px solid #e2e8f0;">',
'                  <td width="35%" style="font-weight:bold; color:#134e4a; padding:8px;">Report Number</td>',
'                  <td style="color:#0d9488; padding:8px;">: <strong>#REPORT_NUMBER#</strong></td>',
'                 </tr>',
'                <tr style="border-bottom:1px solid #e2e8f0;">',
'                  <td width="35%" style="font-weight:bold; color:#134e4a; padding:8px;">Reporter Name</td>',
'                  <td style="padding:8px;">: #REPORTER_NAME#</td>',
'                 </tr>',
'                <tr style="border-bottom:1px solid #e2e8f0;">',
'                  <td width="35%" style="font-weight:bold; color:#134e4a; padding:8px;">Reporter Email</td>',
'                  <td style="padding:8px;">: #REPORTER_EMAIL#</td>',
'                 </tr>',
'                <tr style="border-bottom:1px solid #e2e8f0;">',
'                  <td width="35%" style="font-weight:bold; color:#134e4a; padding:8px;">Accused Name</td>',
'                  <td style="padding:8px;">: <strong>#ACCUSED_NAME#</strong></td>',
'                 </tr>',
'                <tr style="border-bottom:1px solid #e2e8f0;">',
'                  <td width="35%" style="font-weight:bold; color:#134e4a; padding:8px;">Accused Position</td>',
'                  <td style="padding:8px;">: #ACCUSED_POSITION#</td>',
'                 </tr>',
'                <tr style="border-bottom:1px solid #e2e8f0;">',
'                  <td width="35%" style="font-weight:bold; color:#134e4a; padding:8px;">Incident Date</td>',
'                  <td style="padding:8px;">: #INCIDENT_DATE#</td>',
'                 </tr>',
'                <tr>',
'                  <td width="35%" style="font-weight:bold; color:#134e4a; padding:8px;">Incident Location</td>',
'                  <td style="padding:8px;">: #INCIDENT_LOCATION#</td>',
'                 </tr>',
'              </table>',
'',
'              <!-- Chronology Section -->',
'              <table width="100%" cellpadding="0" cellspacing="0" style="margin:20px 0; background:#fef3c7; border-radius:8px; border-left:4px solid #f59e0b;">',
'                <tr>',
'                  <td style="padding:15px;">',
unistr('                    <strong style="color:#92400e;">\D83D\DCD6 Chronology Summary:</strong><br>'),
'                    <p style="margin:8px 0 0 0; color:#78350f;">#KRONOLOGI_SUMMARY#</p>',
'                  </td>',
'                </tr>',
'              </table>',
'',
'              <!-- Attachment Info -->',
'              <table width="100%" cellpadding="0" cellspacing="0" style="margin:20px 0; background:#f1f5f9; border-radius:8px;">',
'                <tr>',
'                  <td style="padding:12px 15px;">',
unistr('                    <strong>\D83D\DCCE Supporting Evidence:</strong> #ATTACHMENT_STATUS#'),
'                  </td>',
'                </tr>',
'              </table>',
'',
'              <p>',
'                Please log in to the WBS system to view the full report details',
'                and take follow-up action according to the applicable SOP.',
'              </p>',
'',
'              <!-- Button -->',
'              <p style="text-align:center;margin:30px 0;">',
unistr('                <a href="#APP_URL#" style="background-color:#0d9488; color:#ffffff; padding:12px 28px; text-decoration:none; border-radius:6px; font-weight:bold; display:inline-block;">\D83D\DD17 Akses WBS System</a>'),
'              </p>',
'',
'              <hr style="border:none; border-top:1px solid #e2e8f0; margin:20px 0;">',
'',
'              <table width="100%" cellpadding="0" cellspacing="0" style="margin:10px 0 0 0; background:#fef2f2; border-radius:8px; border-left:4px solid #ef4444;">',
'                <tr>',
'                  <td style="padding:12px 15px;">',
unistr('                    <strong style="color:#991b1b;">\26A0\FE0F Important Note:</strong><br>'),
'                    <span style="font-size:13px; color:#64748b;">This report is confidential. The reporter identity is protected in accordance with company policy.</span>',
'                  </td>',
'                </tr>',
'              </table>',
'',
'             </td>',
'           </tr>',
'',
'          <!-- Footer -->',
'          <tr>',
'            <td style="background-color: #f9f9f9; padding: 20px; text-align: center; font-size: 12px; color: #888888; border-top: 1px solid #eeeeee;">',
'              <p style="margin:0 0 5px 0;">WBS - Independent Whistleblowing System</p>',
'              <p style="margin:0 0 5px 0;">This is an automated message. Please do not reply to this email.</p>',
unistr('              <p style="margin:0;">\00A9 #CURRENT_YEAR# WBS</p>'),
'             </td>',
'           </tr>',
'',
'        </table>',
'        <!-- End Container -->',
'',
'       </td>',
'     </tr>',
'   </table>',
'',
'</body>'))
,p_html_header=>'<b style="font-size: 24px;" class="text-center">WBS Report Receipt (#REPORT_NUMBER#)</b>'
,p_version_scn=>'SH256:AqMQ9tT1xcRLRuPdj_HixhVayIwzWbM0VMmKjsZW6d8'
);
wwv_flow_imp.component_end;
end;
/
