prompt --application/pages/page_00099
begin
--   Manifest
--     PAGE: 00099
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2026.03.30'
,p_release=>'26.1.1'
,p_default_workspace_id=>13144316281138660209
,p_default_application_id=>125939
,p_default_id_offset=>14279541879556441716
,p_default_owner=>'WKSP_MANUELPORTOFOLIO'
);
wwv_flow_imp_page.create_page(
 p_id=>99
,p_name=>'Landing Page'
,p_alias=>'LANDING-PAGE'
,p_step_title=>'Landing Page'
,p_autocomplete_on_off=>'OFF'
,p_html_page_header=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<!-- TOP NAVIGATION BAR -->',
'<nav class="apex-nav">',
'  <div class="nav-logo">',
'    <svg viewBox="0 0 24 24" fill="white"><path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/></svg>',
'    WBS',
'  </div>',
'  <div class="nav-tabs">',
unistr('    <a class="nav-tab active" href="f?p=&APP_ID.:99:&APP_SESSION.">\D83C\DFE0 Landing Page</a>'),
'  </div>',
'  <div class="nav-right">',
'    <a class="nav-tab" href="f?p=&APP_ID.:9999:&APP_SESSION." style="color: white; text-decoration: none; padding: 0 14px; height: 48px; display: flex; align-items: center; gap: 8px;">',
unistr('      \D83D\DD10 Admin Portal \25B8'),
'    </a>',
'  </div>',
'</nav>',
'',
'<!-- HERO SECTION -->',
'<div class="hero">',
'  <div class="hero-text">',
'    <h1>Welcome to WBS</h1>',
unistr('    <p>A secure and trusted internal whistleblowing platform \2014 report violations, fraud, and unethical conduct safely and confidentially.</p>'),
'    <div class="hero-sub">',
unistr('      <span class="hero-chip">\D83D\DD12 Confidential</span>'),
unistr('      <span class="hero-chip">\2696\FE0F Independent</span>'),
unistr('      <span class="hero-chip">\D83D\DEAB Impartial</span>'),
unistr('      <span class="hero-chip">\D83D\DEE1\FE0F Whistleblower Protection</span>'),
'    </div>',
'  </div>',
unistr('  <div class="hero-icon">\D83D\DEE1\FE0F</div>'),
'</div>'))
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'/* ------------------------- Top Navigation Bar (frosted) ------------------------- */',
'.apex-nav {',
'  background: rgba(10,34,37,0.55);',
'  -webkit-backdrop-filter: blur(16px) saturate(1.4);',
'  backdrop-filter: blur(16px) saturate(1.4);',
'  border-bottom: 1px solid rgba(255,255,255,0.14);',
'  height: 48px;',
'  display: flex;',
'  align-items: center;',
'  padding: 0 16px;',
'  gap: 0;',
'  position: sticky;',
'  top: 0;',
'  z-index: 100;',
'  box-shadow: 0 2px 8px rgba(0,0,0,0.2);',
'}',
'.apex-nav .nav-logo {',
'  color: white;',
'  font-size: 16px;',
'  font-weight: 700;',
'  letter-spacing: 0.3px;',
'  display: flex;',
'  align-items: center;',
'  gap: 8px;',
'  margin-right: 32px;',
'}',
'.apex-nav .nav-logo svg { width: 22px; height: 22px; }',
'.apex-nav .nav-tabs { display: flex; gap: 2px; flex: 1; }',
'.apex-nav .nav-tab {',
'  color: rgba(255,255,255,0.75);',
'  font-size: 13px;',
'  padding: 0 14px;',
'  height: 48px;',
'  display: flex;',
'  align-items: center;',
'  cursor: pointer;',
'  border-bottom: 3px solid transparent;',
'  text-decoration: none;',
'  transition: all 0.15s;',
'}',
'.apex-nav .nav-tab:hover { color: white; background: rgba(255,255,255,0.08); }',
'.apex-nav .nav-tab.active { color: white; border-bottom-color: #2dd4bf; background: rgba(255,255,255,0.06); }',
'.apex-nav .nav-right {',
'  display: flex;',
'  align-items: center;',
'  gap: 8px;',
'  margin-left: auto;',
'}',
'.apex-nav .nav-icon-btn {',
'  width: 32px; height: 32px;',
'  border-radius: 50%;',
'  background: rgba(255,255,255,0.1);',
'  border: none;',
'  color: rgba(255,255,255,0.8);',
'  cursor: pointer;',
'  display: flex; align-items: center; justify-content: center;',
'  font-size: 14px;',
'}',
'.apex-nav .nav-icon-btn:hover { background: rgba(255,255,255,0.2); }',
'.apex-nav .nav-user {',
'  display: flex;',
'  align-items: center;',
'  gap: 8px;',
'  color: rgba(255,255,255,0.85);',
'  font-size: 13px;',
'  cursor: pointer;',
'  padding: 4px 10px;',
'  border-radius: 6px;',
'}',
'.apex-nav .nav-user:hover { background: rgba(255,255,255,0.1); }',
'.apex-nav .nav-user .avatar {',
'  width: 28px; height: 28px;',
'  border-radius: 50%;',
'  background: #0d9488;',
'  display: flex; align-items: center; justify-content: center;',
'  font-size: 12px;',
'  font-weight: 700;',
'  color: white;',
'}',
'/* -------------------------------------------------------------------------------------------- */',
'/* ------------------------------- Hero Section (liquid glass) ------------------------------- */',
'.hero {',
'  background: linear-gradient(135deg, rgba(19,78,74,0.50) 0%, rgba(13,148,136,0.42) 55%, rgba(34,211,238,0.30) 120%);',
'  -webkit-backdrop-filter: blur(20px) saturate(1.5);',
'  backdrop-filter: blur(20px) saturate(1.5);',
'  border: 1px solid rgba(255,255,255,0.28);',
'  border-radius: 22px;',
'  margin: 14px;',
'  box-shadow: 0 22px 50px -20px rgba(2,24,26,0.6), inset 0 1px 0 rgba(255,255,255,0.30);',
'  padding: 48px 40px;',
'  display: flex;',
'  align-items: center;',
'  gap: 32px;',
'  min-height: 220px;',
'  position: relative;',
'  overflow: hidden;',
'  animation: fadeIn 0.6s ease-out;',
'}',
'/* Animated background dots pattern */',
'.hero::before {',
'  content: '''';',
'  position: absolute;',
'  top: 0;',
'  left: 0;',
'  right: 0;',
'  bottom: 0;',
'  background-image: radial-gradient(rgba(255,255,255,0.08) 1px, transparent 1px);',
'  background-size: 24px 24px;',
'  pointer-events: none;',
'}',
'.hero-text h1 {',
'  font-size: 28px;',
'  font-weight: 700;',
'  color: white;',
'  margin-bottom: 8px;',
'  text-shadow: 0 0 18px rgba(45,212,191,0.4);',
'}',
'.hero-text p {',
'  color: rgba(255,255,255,0.8);',
'  font-size: 15px;',
'  line-height: 1.6;',
'  max-width: 560px;',
'}',
'.hero-text .hero-sub {',
'  margin-top: 16px;',
'  display: flex;',
'  gap: 12px;',
'  flex-wrap: wrap;',
'}',
'.hero-icon {',
'  cursor: default;',
'  margin-left: auto;',
'  width: 120px;',
'  height: 120px;',
'  background: rgba(255,255,255,0.1);',
'  border: 1px solid rgba(255,255,255,0.2);',
'  border-radius: 24px;',
'  display: flex;',
'  align-items: center;',
'  justify-content: center;',
'  font-size: 56px;',
'  flex-shrink: 0;',
'  animation: float 4s ease-in-out infinite;',
'  transition: all 0.3s ease;',
'}',
'.hero-icon:hover {',
'  transform: scale(1.05);',
'  background: rgba(255,255,255,0.2);',
'  box-shadow: 0 0 30px rgba(45,212,191,0.35);',
'}',
'@keyframes float {',
'  0% { transform: translateY(0px); }',
'  50% { transform: translateY(-10px); }',
'  100% { transform: translateY(0px); }',
'}',
'@keyframes fadeIn {',
'  from { opacity: 0; }',
'  to { opacity: 1; }',
'}',
'/* -------------------------------------------------------------------------------------------- */',
'/* ------------------------------ Hero Chips Hover Effect ------------------------------ */',
'.hero-chip {',
'  transition: all 0.3s ease-in-out;',
'  cursor: default;',
'  position: relative;',
'  background: rgba(255,255,255,0.15);',
'  border: 1px solid rgba(255,255,255,0.3);',
'  color: rgba(255,255,255,0.9);',
'  font-size: 12px;',
'  padding: 4px 12px;',
'  border-radius: 20px;',
'  backdrop-filter: blur(4px);',
'}',
'.hero-chip:hover {',
'  background: linear-gradient(135deg, rgba(34, 211, 238, 0.2), rgba(45, 212, 191, 0.2));',
'  border: 1px solid rgba(34, 211, 238, 0.6);',
'  box-shadow: 0 8px 20px rgba(34, 211, 238, 0.3), 0 0 0 1px rgba(45, 212, 191, 0.2);',
'  color: white;',
'  text-shadow: 0 0 4px rgba(45, 212, 191, 0.5);',
'}',
'/* -------------------------------------------------------------------------------------------- */',
'/* ------------------------------ Section Title (light on dark) ------------------------------ */',
'.section-title {',
'  font-size: 14px;',
'  font-weight: 700;',
'  color: rgba(226,253,249,0.75);',
'  text-transform: uppercase;',
'  letter-spacing: 0.6px;',
'  margin-bottom: 16px;',
'  margin-top: 16px;',
'  display: flex;',
'  align-items: center;',
'  gap: 8px;',
'  text-shadow: 0 0 12px rgba(45,212,191,0.3);',
'}',
'.section-title::after {',
'  content: '''';',
'  flex: 1;',
'  height: 2px;',
'  background: linear-gradient(90deg, transparent, rgba(45,212,191,0.6), transparent);',
'}',
'/* -------------------------------------------------------------------------------------------- */',
'/* --------------------------- Navigation Cards (dark liquid glass) --------------------------- */',
'.cards-grid {',
'  display: grid;',
'  grid-template-columns: repeat(2, 1fr);',
'  gap: 16px;',
'  margin-bottom: 40px;',
'}',
'.nav-card {',
'  background: linear-gradient(160deg, rgba(13,42,45,0.50) 0%, rgba(7,24,28,0.66) 100%);',
'  -webkit-backdrop-filter: blur(28px) saturate(1.6);',
'  backdrop-filter: blur(28px) saturate(1.6);',
'  border: 1px solid rgba(255,255,255,0.16);',
'  border-radius: 20px;',
'  padding: 28px 20px;',
'  text-decoration: none;',
'  color: inherit;',
'  display: flex;',
'  flex-direction: column;',
'  align-items: center;',
'  text-align: center;',
'  gap: 14px;',
'  transition: all 0.3s cubic-bezier(0.2, 0.9, 0.4, 1.1);',
'  cursor: pointer;',
'  position: relative;',
'  overflow: hidden;',
'  box-shadow: 0 20px 45px -18px rgba(0,0,0,0.5), inset 0 1px 0 rgba(255,255,255,0.15);',
'  animation: fadeInUp 0.5s ease-out backwards;',
'}',
'.nav-card:first-child { animation-delay: 0.1s; }',
'.nav-card:last-child { animation-delay: 0.2s; }',
'@keyframes fadeInUp {',
'  from {',
'    opacity: 0;',
'    transform: translateY(30px);',
'  }',
'  to {',
'    opacity: 1;',
'    transform: translateY(0);',
'  }',
'}',
'.nav-card::before {',
'  content: '''';',
'  position: absolute;',
'  top: 0; left: 0; right: 0;',
'  height: 3px;',
'  background: transparent;',
'  transition: background 0.2s;',
'}',
'.nav-card:hover {',
'  transform: translateY(-4px);',
'  box-shadow: 0 24px 50px -18px rgba(0,0,0,0.6), 0 0 26px rgba(45,212,191,0.20);',
'  border-color: rgba(45,212,191,0.45);',
'  background: linear-gradient(160deg, rgba(16,52,55,0.58) 0%, rgba(9,30,34,0.72) 100%);',
'}',
'.nav-card:hover::before { background: linear-gradient(90deg, #2dd4bf, #22d3ee); }',
'.nav-card .card-icon {',
'  width: 60px; height: 60px;',
'  border-radius: 16px;',
'  background: rgba(45,212,191,0.14);',
'  border: 1px solid rgba(45,212,191,0.25);',
'  display: flex; align-items: center; justify-content: center;',
'  font-size: 26px;',
'  transition: all 0.3s ease;',
'}',
'.nav-card:hover .card-icon {',
'  background: rgba(45,212,191,0.26);',
'  box-shadow: 0 0 18px rgba(45,212,191,0.3);',
'  transform: scale(1.08) rotate(2deg);',
'}',
'.nav-card h3 { font-size: 14px; font-weight: 700; color: #eafffb; text-shadow: 0 0 12px rgba(45,212,191,0.35); }',
'.nav-card p { font-size: 12px; color: rgba(167,220,212,0.8); line-height: 1.5; }',
'.nav-card .card-link {',
'  font-size: 12px;',
'  color: #5eead4;',
'  font-weight: 600;',
'  margin-top: auto;',
'}',
'/* -------------------------------------------------------------------------------------------- */',
'/* ------------------------------ GLOBAL STYLE (aurora body) ------------------------------ */',
'html {',
'  scroll-behavior: smooth;',
'}',
'body {',
'  background: radial-gradient(1100px 700px at 8% -12%, rgba(45,212,191,0.30), transparent 60%), radial-gradient(1000px 650px at 108% 8%, rgba(34,211,238,0.24), transparent 55%), radial-gradient(900px 900px at 50% 118%, rgba(13,148,136,0.22), transpar'
||'ent 62%), linear-gradient(160deg, #071a1e 0%, #0b2b30 45%, #0d3a3d 100%) !important;',
'  background-attachment: fixed !important;',
'  font-family: system-ui, -apple-system, ''Segoe UI'', Roboto, ''Helvetica Neue'', sans-serif;',
'}',
'/* Container max-width */',
'.container {',
'  max-width: 1280px;',
'}',
'/* -------------------------------------------------------------------------------------------- */',
'/* ------------------------------ INFO BANNER (dark liquid glass) ------------------------------ */',
'div[style*="background:white;border:1px solid #e2e8f0;border-left:4px solid #0d9488"] {',
'  background: linear-gradient(160deg, rgba(13,42,45,0.55), rgba(7,24,28,0.68)) !important;',
'  -webkit-backdrop-filter: blur(20px) saturate(1.5);',
'  backdrop-filter: blur(20px) saturate(1.5);',
'  border-color: rgba(255,255,255,0.18) !important;',
'  border-left-color: #2dd4bf !important;',
'  transition: all 0.3s ease;',
'  box-shadow: 0 12px 30px -12px rgba(0,0,0,0.5), inset 0 1px 0 rgba(255,255,255,0.15);',
'  border-radius: 14px !important;',
'}',
'div[style*="background:white;border:1px solid #e2e8f0;border-left:4px solid #0d9488"]:hover {',
'  transform: translateY(-2px);',
'  box-shadow: 0 16px 34px -12px rgba(0,0,0,0.55), 0 0 22px rgba(45,212,191,0.18);',
'  border-left-width: 6px;',
'}',
'/* Light text inside the banner (overrides the inline dark colors) */',
'div[style*="background:white;border:1px solid #e2e8f0;border-left:4px solid #0d9488"] div[style*="color:#134e4a"] {',
'  color: #7df3e1 !important;',
'  text-shadow: 0 0 12px rgba(45,212,191,0.35);',
'}',
'div[style*="background:white;border:1px solid #e2e8f0;border-left:4px solid #0d9488"] div[style*="color:#64748b"] {',
'  color: rgba(203,236,231,0.8) !important;',
'}',
'/* -------------------------------------------------------------------------------------------- */',
'/* ------------------------------ REGION CARD (dark liquid glass) ------------------------------ */',
'.t-Region {',
'  background: transparent !important;',
'  box-shadow: none !important;',
'  border: none !important;',
'  -webkit-backdrop-filter: none !important;',
'  backdrop-filter: none !important;',
'  overflow: visible !important;',
'}',
'.t-Region-bodyWrap {',
'  background: linear-gradient(160deg, rgba(13,42,45,0.50) 0%, rgba(7,24,28,0.66) 100%) !important;',
'  -webkit-backdrop-filter: blur(28px) saturate(1.6);',
'  backdrop-filter: blur(28px) saturate(1.6);',
'  border: 1px solid rgba(255,255,255,0.16) !important;',
'  border-radius: 24px !important;',
'  box-shadow: 0 30px 60px -18px rgba(0,0,0,0.55), inset 0 1px 0 rgba(255,255,255,0.18) !important;',
'  padding: 14px !important;',
'  position: relative;',
'  transition: all 0.3s ease;',
'}',
'.t-Region-bodyWrap:hover {',
'  border-color: rgba(45,212,191,0.35) !important;',
'}',
'.t-Region-header {',
'  background: transparent !important;',
'  border-bottom: none !important;',
'}',
'.t-Region-header .t-Region-title,',
'.t-Region .t-Region-title {',
'  color: #eafffb !important;',
'  text-shadow: 0 0 14px rgba(45,212,191,0.4);',
'}',
'/* -------------------------------------------------------------------------------------------- */',
'/* ------------------------------ CUSTOM SCROLLBAR (dark neon) ------------------------------ */',
'::-webkit-scrollbar {',
'  width: 8px;',
'  height: 8px;',
'}',
'::-webkit-scrollbar-track {',
'  background: rgba(7,26,30,0.45);',
'  border-radius: 10px;',
'}',
'::-webkit-scrollbar-thumb {',
'  background: linear-gradient(135deg, #14b8a6, #22d3ee);',
'  border-radius: 10px;',
'}',
'::-webkit-scrollbar-thumb:hover {',
'  background: linear-gradient(135deg, #2dd4bf, #22d3ee);',
'}',
'/* -------------------------------------------------------------------------------------------- */',
'/* ------------------------------ RESPONSIVE TWEAKS ------------------------------ */',
'@media (max-width: 768px) {',
'  .hero {',
'    flex-direction: column;',
'    text-align: center;',
'    padding: 32px 24px;',
'  }',
'',
'  .hero-text p {',
'    max-width: 100%;',
'  }',
'',
'  .hero-icon {',
'    margin-left: 0;',
'    margin-top: 16px;',
'  }',
'',
'  .cards-grid {',
'    grid-template-columns: 1fr !important;',
'    gap: 20px;',
'  }',
'',
'  .nav-card {',
'    padding: 24px 16px;',
'  }',
'',
'  .apex-nav {',
'    flex-wrap: wrap;',
'    height: auto;',
'    padding: 8px 12px;',
'  }',
'',
'  .apex-nav .nav-logo {',
'    margin-right: auto;',
'  }',
'',
'  .apex-nav .nav-tabs {',
'    order: 3;',
'    flex-basis: 100%;',
'    margin-top: 8px;',
'    justify-content: center;',
'  }',
'',
'  .apex-nav .nav-tab {',
'    padding: 0 10px;',
'    font-size: 12px;',
'  }',
'}',
'@media (max-width: 480px) {',
'  .hero-text h1 {',
'    font-size: 22px;',
'  }',
'',
'  .hero-text p {',
'    font-size: 13px;',
'  }',
'',
'  .hero-sub {',
'    justify-content: center;',
'  }',
'',
'  .section-title {',
'    font-size: 12px;',
'  }',
'}',
'/* -------------------------------------------------------------------------------------------- */',
''))
,p_step_template=>wwv_flow_imp.id(14344309855693909385)
,p_page_template_options=>'#DEFAULT#'
,p_page_is_public_y_n=>'Y'
,p_protection_level=>'C'
,p_page_component_map=>'11'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(14344816647534969520)
,p_plug_name=>'Info Banner'
,p_static_id=>'info-banner'
,p_region_template_options=>'#DEFAULT#:margin-bottom-lg:margin-left-lg:margin-right-lg'
,p_plug_template=>wwv_flow_imp.id(14344337289386909406)
,p_plug_display_sequence=>10
,p_plug_display_point=>'REGION_POSITION_02'
,p_plug_item_display_point=>'ABOVE'
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'  <!-- Info Banner -->',
'  <div style="background:white;border:1px solid #e2e8f0;border-left:4px solid #0d9488;border-radius:8px;padding:18px 20px;display:flex;align-items:flex-start;gap:14px;">',
unistr('    <span style="font-size:22px;flex-shrink:0;">\2139\FE0F</span>'),
'    <div>',
'      <div style="font-weight:700;color:#134e4a;margin-bottom:4px;">Your Identity Stays Confidential</div>',
'      <div style="font-size:13px;color:#64748b;line-height:1.6;">The reporter identity is guaranteed confidential. You may report anonymously. Every report is handled seriously and professionally.</div>',
'    </div>',
'  </div>',
'',
'</div>'))
,p_required_patch=>wwv_flow_imp.id(14344300039949909298)
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(14344816748132969521)
,p_plug_name=>'Navigation Cards'
,p_static_id=>'navigation-cards'
,p_region_template_options=>'#DEFAULT#:t-Region--hideHeader:t-Region--noBorder:t-Region--scrollBody:margin-left-lg:margin-right-lg'
,p_plug_template=>wwv_flow_imp.id(14344403920753909451)
,p_plug_display_sequence=>10
,p_plug_item_display_point=>'ABOVE'
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<!-- Navigation Cards -->',
'  <div class="section-title">Menu Utama</div>',
'  <div class="cards-grid">',
'    <!-- <a class="nav-card" href="f?p=&APP_ID.:3:&APP_SESSION."> -->',
'    <a class="nav-card" href="f?p=&APP_ID.:3:&APP_SESSION.">',
unistr('      <div class="card-icon">\D83D\DCDD</div>'),
'      <h3>Submit a Report</h3>',
'      <p>Report violations, fraud, or unethical conduct safely</p>',
unistr('      <span class="card-link">Start Reporting \2192</span>'),
'    </a>',
'    <!-- <a class="nav-card" href="f?p=&APP_ID.:6:&APP_SESSION."> -->',
'    <a class="nav-card" href="f?p=&APP_ID.:6:&APP_SESSION.">',
unistr('      <div class="card-icon">\D83D\DD0D</div> <!--\D83D\DCD6-->'),
'      <h3>Track Report</h3>',
'      <p>Track the progress of your report</p>',
unistr('      <span class="card-link">Track Report \2192</span>'),
'    </a>',
'  </div>'))
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp.component_end;
end;
/
