prompt --application/deployment/install/install_wbs_installation
begin
--   Manifest
--     INSTALL: INSTALL-WBS Installation
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2026.03.30'
,p_release=>'26.1.1'
,p_default_workspace_id=>13144316281138660209
,p_default_application_id=>125939
,p_default_id_offset=>14279541879556441716
,p_default_owner=>'WKSP_MANUELPORTOFOLIO'
);
wwv_flow_imp.g_varchar2_table := wwv_flow_imp.empty_varchar2_table;
wwv_flow_imp.g_varchar2_table(1) := '  CREATE TABLE "XTD_WBS" '||wwv_flow.LF||
'   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVA';
wwv_flow_imp.g_varchar2_table(2) := 'LUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSC';
wwv_flow_imp.g_varchar2_table(3) := 'ALE  NOT NULL ENABLE, '||wwv_flow.LF||
'	"NAMA_PELAPOR" VARCHAR2(4000 CHAR), '||wwv_flow.LF||
'	"TELP_PELAPOR" VARCHAR2(4000 CHAR), '||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(4) := '"EMAIL_PELAPOR" VARCHAR2(255 CHAR), '||wwv_flow.LF||
'	"TINDAKAN" VARCHAR2(4000 CHAR), '||wwv_flow.LF||
'	"NAMA_TERLAPOR" VARCHAR2(400';
wwv_flow_imp.g_varchar2_table(5) := '0 CHAR), '||wwv_flow.LF||
'	"JABATAN_TERLAPOR" VARCHAR2(4000 CHAR), '||wwv_flow.LF||
'	"WAKTU_KEJADIAN" VARCHAR2(4000 CHAR), '||wwv_flow.LF||
'	"LOKASI';
wwv_flow_imp.g_varchar2_table(6) := '_KEJADIAN" VARCHAR2(4000 CHAR), '||wwv_flow.LF||
'	"KRONOLOGIS_KEJADIAN" VARCHAR2(4000 CHAR), '||wwv_flow.LF||
'	"NOMINAL" VARCHAR2(40';
wwv_flow_imp.g_varchar2_table(7) := '00 CHAR), '||wwv_flow.LF||
'	"FILE_BLOB" BLOB, '||wwv_flow.LF||
'	"STATUS" VARCHAR2(50), '||wwv_flow.LF||
'	"NOMOR_LAPORAN" VARCHAR2(255 CHAR), '||wwv_flow.LF||
'	"MIME';
wwv_flow_imp.g_varchar2_table(8) := '_TYPE" VARCHAR2(255), '||wwv_flow.LF||
'	"LAST_UPDATE_DATE" DATE, '||wwv_flow.LF||
'	"FILE_NAME" VARCHAR2(255 CHAR), '||wwv_flow.LF||
'	"PIC" VARCHAR2(';
wwv_flow_imp.g_varchar2_table(9) := '255 CHAR), '||wwv_flow.LF||
'	"FEEDBACK" VARCHAR2(4000), '||wwv_flow.LF||
'	"CREATED_DATE" DATE, '||wwv_flow.LF||
'	"CREATED_BY" VARCHAR2(255 CHAR), '||wwv_flow.LF||
'	';
wwv_flow_imp.g_varchar2_table(10) := '"UPDATED_DATE" DATE, '||wwv_flow.LF||
'	"UPDATED_BY" VARCHAR2(255 CHAR), '||wwv_flow.LF||
'	"JABATAN_PELAPOR" VARCHAR2(255 CHAR), '||wwv_flow.LF||
'	"J';
wwv_flow_imp.g_varchar2_table(11) := 'ENIS_BUKTI_PENDUKUNG" VARCHAR2(2000 CHAR), '||wwv_flow.LF||
'	"HASIL_VERIFIKASI" VARCHAR2(4000 CHAR), '||wwv_flow.LF||
'	"NO_BERITA_AC';
wwv_flow_imp.g_varchar2_table(12) := 'ARA_TINDAK_LANJUT" VARCHAR2(255 CHAR), '||wwv_flow.LF||
'	"TIM_INVESTIGASI" VARCHAR2(255 CHAR), '||wwv_flow.LF||
'	"RESULT_SUMMARY" VA';
wwv_flow_imp.g_varchar2_table(13) := 'RCHAR2(2000 CHAR), '||wwv_flow.LF||
'	"NOTES" VARCHAR2(4000 CHAR), '||wwv_flow.LF||
'	"KATEGORI_PELANGGARAN" VARCHAR2(255 CHAR), '||wwv_flow.LF||
'	"SO';
wwv_flow_imp.g_varchar2_table(14) := 'URCE" VARCHAR2(255 CHAR), '||wwv_flow.LF||
'	 CONSTRAINT "XTD_WBS_ID_PK" PRIMARY KEY ("ID")'||wwv_flow.LF||
'  USING INDEX  ENABLE'||wwv_flow.LF||
'   ';
wwv_flow_imp.g_varchar2_table(15) := ') ;'||wwv_flow.LF||
''||wwv_flow.LF||
'  CREATE TABLE "XTD_WBS_BLOB" '||wwv_flow.LF||
'   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVAL';
wwv_flow_imp.g_varchar2_table(16) := 'UE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NO';
wwv_flow_imp.g_varchar2_table(17) := 'KEEP  NOSCALE  NOT NULL ENABLE, '||wwv_flow.LF||
'	"FILE_NAME" VARCHAR2(4000 CHAR), '||wwv_flow.LF||
'	"FILE_MIME_TYPE" VARCHAR2(255 C';
wwv_flow_imp.g_varchar2_table(18) := 'HAR), '||wwv_flow.LF||
'	"FILE_BLOB_DATED" DATE, '||wwv_flow.LF||
'	"FILE_BLOB" BLOB, '||wwv_flow.LF||
'	"WBS_ID" NUMBER, '||wwv_flow.LF||
'	"CREATED_DATE" DATE, '||wwv_flow.LF||
'	"CRE';
wwv_flow_imp.g_varchar2_table(19) := 'ATED_BY" VARCHAR2(255 CHAR), '||wwv_flow.LF||
'	"UPDATED_DATE" DATE, '||wwv_flow.LF||
'	"UPDATED_BY" VARCHAR2(255 CHAR), '||wwv_flow.LF||
'	 CONSTRAINT';
wwv_flow_imp.g_varchar2_table(20) := ' "XTD_WBS_BLOB_PK" PRIMARY KEY ("ID")'||wwv_flow.LF||
'  USING INDEX  ENABLE'||wwv_flow.LF||
'   ) ;'||wwv_flow.LF||
''||wwv_flow.LF||
'   COMMENT ON COLUMN "XTD_WBS"."';
wwv_flow_imp.g_varchar2_table(21) := 'KRONOLOGIS_KEJADIAN" IS ''Full detailed incident chronology'';'||wwv_flow.LF||
'   COMMENT ON COLUMN "XTD_WBS"."JENIS_B';
wwv_flow_imp.g_varchar2_table(22) := 'UKTI_PENDUKUNG" IS ''Supporting evidence type, e.g. goods receipt form, invoice, voice recording, PO,';
wwv_flow_imp.g_varchar2_table(23) := ' incoming QC checksheet, etc.'';'||wwv_flow.LF||
'   COMMENT ON COLUMN "XTD_WBS"."HASIL_VERIFIKASI" IS ''Document verif';
wwv_flow_imp.g_varchar2_table(24) := 'ication result: supporting documents provided / no supporting documents'';'||wwv_flow.LF||
'   COMMENT ON COLUMN "XTD_';
wwv_flow_imp.g_varchar2_table(25) := 'WBS"."NO_BERITA_ACARA_TINDAK_LANJUT" IS ''Follow-up memo number (format: FUP/YYYY/XXXX)'';'||wwv_flow.LF||
'   COMMENT ';
wwv_flow_imp.g_varchar2_table(26) := 'ON COLUMN "XTD_WBS"."TIM_INVESTIGASI" IS ''Team performing the investigation (e.g. Internal Audit, HR';
wwv_flow_imp.g_varchar2_table(27) := 'BP, etc.)'';'||wwv_flow.LF||
'   COMMENT ON COLUMN "XTD_WBS"."RESULT_SUMMARY" IS ''Summary of investigation results and';
wwv_flow_imp.g_varchar2_table(28) := ' conclusions'';'||wwv_flow.LF||
'   COMMENT ON COLUMN "XTD_WBS"."SOURCE" IS ''Channel through which the report was rece';
wwv_flow_imp.g_varchar2_table(29) := 'ived'';'||wwv_flow.LF||
''||wwv_flow.LF||
'  CREATE OR REPLACE EDITIONABLE TRIGGER "XTD_WBS_BIU" '||wwv_flow.LF||
'BEFORE INSERT OR UPDATE ON XTD_WBS   ';
wwv_flow_imp.g_varchar2_table(30) := ''||wwv_flow.LF||
'FOR EACH ROW   '||wwv_flow.LF||
'BEGIN   '||wwv_flow.LF||
'    -- If new record data '||wwv_flow.LF||
'    IF INSERTING THEN '||wwv_flow.LF||
'        :NEW.CREATED_DAT';
wwv_flow_imp.g_varchar2_table(31) := 'E := COALESCE(:NEW.CREATED_DATE, SYSDATE);   '||wwv_flow.LF||
'        :NEW.CREATED_BY := COALESCE(:NEW.CREATED_BY, A';
wwv_flow_imp.g_varchar2_table(32) := 'PEX_APPLICATION.g_user);   '||wwv_flow.LF||
'    END IF;   '||wwv_flow.LF||
'       '||wwv_flow.LF||
'    -- If updating old record data '||wwv_flow.LF||
'    IF UPDATI';
wwv_flow_imp.g_varchar2_table(33) := 'NG THEN   '||wwv_flow.LF||
'        IF :OLD.CREATED_DATE IS NULL THEN   '||wwv_flow.LF||
'            :NEW.CREATED_DATE := SYSDATE;   ';
wwv_flow_imp.g_varchar2_table(34) := ''||wwv_flow.LF||
'            :NEW.CREATED_BY := APEX_APPLICATION.g_user;   '||wwv_flow.LF||
'        END IF;   '||wwv_flow.LF||
'           '||wwv_flow.LF||
'        I';
wwv_flow_imp.g_varchar2_table(35) := 'F :OLD.UPDATED_DATE IS NULL OR :OLD.UPDATED_BY IS NULL OR   '||wwv_flow.LF||
'           :OLD.UPDATED_DATE != :NEW.UP';
wwv_flow_imp.g_varchar2_table(36) := 'DATED_DATE OR :OLD.UPDATED_BY != :NEW.UPDATED_BY THEN   '||wwv_flow.LF||
'            :NEW.UPDATED_DATE := SYSDATE;  ';
wwv_flow_imp.g_varchar2_table(37) := ' '||wwv_flow.LF||
'            :NEW.UPDATED_BY := APEX_APPLICATION.g_user;   '||wwv_flow.LF||
'        END IF;   '||wwv_flow.LF||
'    END IF;   '||wwv_flow.LF||
'END;'||wwv_flow.LF||
'';
wwv_flow_imp.g_varchar2_table(38) := '/'||wwv_flow.LF||
'ALTER TRIGGER "XTD_WBS_BIU" ENABLE;'||wwv_flow.LF||
''||wwv_flow.LF||
'  ALTER TABLE "XTD_WBS_BLOB" ADD CONSTRAINT "XTD_WBS_BLOB_FK"';
wwv_flow_imp.g_varchar2_table(39) := ' FOREIGN KEY ("WBS_ID")'||wwv_flow.LF||
'	  REFERENCES "XTD_WBS" ("ID") ON DELETE CASCADE ENABLE;'||wwv_flow.LF||
''||wwv_flow.LF||
'  CREATE OR REPLAC';
wwv_flow_imp.g_varchar2_table(40) := 'E EDITIONABLE TRIGGER "XTD_WBS_BLOB_BIU" '||wwv_flow.LF||
'BEFORE INSERT OR UPDATE ON XTD_WBS_BLOB   '||wwv_flow.LF||
'FOR EACH ROW   ';
wwv_flow_imp.g_varchar2_table(41) := ''||wwv_flow.LF||
'BEGIN   '||wwv_flow.LF||
'    -- If new record data '||wwv_flow.LF||
'    IF INSERTING THEN '||wwv_flow.LF||
'        :NEW.CREATED_DATE := COALESCE(:N';
wwv_flow_imp.g_varchar2_table(42) := 'EW.CREATED_DATE, SYSDATE);   '||wwv_flow.LF||
'        :NEW.CREATED_BY := COALESCE(:NEW.CREATED_BY, APEX_APPLICATION.';
wwv_flow_imp.g_varchar2_table(43) := 'g_user);   '||wwv_flow.LF||
'    END IF;   '||wwv_flow.LF||
'       '||wwv_flow.LF||
'    -- If updating old record data '||wwv_flow.LF||
'    IF UPDATING THEN   '||wwv_flow.LF||
'     ';
wwv_flow_imp.g_varchar2_table(44) := '   IF :OLD.CREATED_DATE IS NULL THEN   '||wwv_flow.LF||
'            :NEW.CREATED_DATE := SYSDATE;   '||wwv_flow.LF||
'            :NE';
wwv_flow_imp.g_varchar2_table(45) := 'W.CREATED_BY := APEX_APPLICATION.g_user;   '||wwv_flow.LF||
'        END IF;   '||wwv_flow.LF||
'           '||wwv_flow.LF||
'        IF :OLD.UPDATED_D';
wwv_flow_imp.g_varchar2_table(46) := 'ATE IS NULL OR :OLD.UPDATED_BY IS NULL OR   '||wwv_flow.LF||
'           :OLD.UPDATED_DATE != :NEW.UPDATED_DATE OR :O';
wwv_flow_imp.g_varchar2_table(47) := 'LD.UPDATED_BY != :NEW.UPDATED_BY THEN   '||wwv_flow.LF||
'            :NEW.UPDATED_DATE := SYSDATE;   '||wwv_flow.LF||
'            :N';
wwv_flow_imp.g_varchar2_table(48) := 'EW.UPDATED_BY := APEX_APPLICATION.g_user;   '||wwv_flow.LF||
'        END IF;   '||wwv_flow.LF||
'    END IF;   '||wwv_flow.LF||
'END;'||wwv_flow.LF||
'/'||wwv_flow.LF||
'ALTER TRIGGER ';
wwv_flow_imp.g_varchar2_table(49) := '"XTD_WBS_BLOB_BIU" ENABLE;'||wwv_flow.LF||
''||wwv_flow.LF||
''||wwv_flow.LF||
'   CREATE SEQUENCE  "XTD_WBS_NO"  MINVALUE 1 MAXVALUE 99999999999999999';
wwv_flow_imp.g_varchar2_table(50) := '99999999999 INCREMENT BY 1 START WITH 69 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;'||wwv_flow.LF||
''||wwv_flow.LF||
'   CR';
wwv_flow_imp.g_varchar2_table(51) := 'EATE SEQUENCE  "XTD_WBS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START ';
wwv_flow_imp.g_varchar2_table(52) := 'WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;'||wwv_flow.LF||
''||wwv_flow.LF||
'   CREATE SEQUENCE  "XTD_WBS_BLOB_SEQ" ';
wwv_flow_imp.g_varchar2_table(53) := ' MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCY';
wwv_flow_imp.g_varchar2_table(54) := 'CLE  NOKEEP  NOSCALE  GLOBAL ;'||wwv_flow.LF||
''||wwv_flow.LF||
'   CREATE SEQUENCE  "XTD_NO_BATL"  MINVALUE 1 MAXVALUE 9999999999999';
wwv_flow_imp.g_varchar2_table(55) := '999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;'||wwv_flow.LF||
''||wwv_flow.LF||
''||wwv_flow.LF||
'c';
wwv_flow_imp.g_varchar2_table(56) := 'reate or replace TRIGGER "XTD_WBS_BIU"  '||wwv_flow.LF||
'BEFORE INSERT OR UPDATE ON XTD_WBS   '||wwv_flow.LF||
'FOR EACH ROW   '||wwv_flow.LF||
'BEGIN';
wwv_flow_imp.g_varchar2_table(57) := '   '||wwv_flow.LF||
'    -- If new record data '||wwv_flow.LF||
'    IF INSERTING THEN '||wwv_flow.LF||
'        :NEW.CREATED_DATE := COALESCE(:NEW.CRE';
wwv_flow_imp.g_varchar2_table(58) := 'ATED_DATE, SYSDATE);   '||wwv_flow.LF||
'        :NEW.CREATED_BY := COALESCE(:NEW.CREATED_BY, APEX_APPLICATION.g_user';
wwv_flow_imp.g_varchar2_table(59) := ');   '||wwv_flow.LF||
'    END IF;   '||wwv_flow.LF||
'       '||wwv_flow.LF||
'    -- If updating old record data '||wwv_flow.LF||
'    IF UPDATING THEN   '||wwv_flow.LF||
'        IF ';
wwv_flow_imp.g_varchar2_table(60) := ':OLD.CREATED_DATE IS NULL THEN   '||wwv_flow.LF||
'            :NEW.CREATED_DATE := SYSDATE;   '||wwv_flow.LF||
'            :NEW.CREA';
wwv_flow_imp.g_varchar2_table(61) := 'TED_BY := APEX_APPLICATION.g_user;   '||wwv_flow.LF||
'        END IF;   '||wwv_flow.LF||
'           '||wwv_flow.LF||
'        IF :OLD.UPDATED_DATE IS';
wwv_flow_imp.g_varchar2_table(62) := ' NULL OR :OLD.UPDATED_BY IS NULL OR   '||wwv_flow.LF||
'           :OLD.UPDATED_DATE != :NEW.UPDATED_DATE OR :OLD.UPD';
wwv_flow_imp.g_varchar2_table(63) := 'ATED_BY != :NEW.UPDATED_BY THEN   '||wwv_flow.LF||
'            :NEW.UPDATED_DATE := SYSDATE;   '||wwv_flow.LF||
'            :NEW.UPD';
wwv_flow_imp.g_varchar2_table(64) := 'ATED_BY := APEX_APPLICATION.g_user;   '||wwv_flow.LF||
'        END IF;   '||wwv_flow.LF||
'    END IF;   '||wwv_flow.LF||
'END;'||wwv_flow.LF||
'/'||wwv_flow.LF||
'create or replace TR';
wwv_flow_imp.g_varchar2_table(65) := 'IGGER "XTD_WBS_BLOB_BIU"  '||wwv_flow.LF||
'BEFORE INSERT OR UPDATE ON XTD_WBS_BLOB   '||wwv_flow.LF||
'FOR EACH ROW   '||wwv_flow.LF||
'BEGIN   '||wwv_flow.LF||
'    -';
wwv_flow_imp.g_varchar2_table(66) := '- If new record data '||wwv_flow.LF||
'    IF INSERTING THEN '||wwv_flow.LF||
'        :NEW.CREATED_DATE := COALESCE(:NEW.CREATED_DATE';
wwv_flow_imp.g_varchar2_table(67) := ', SYSDATE);   '||wwv_flow.LF||
'        :NEW.CREATED_BY := COALESCE(:NEW.CREATED_BY, APEX_APPLICATION.g_user);   '||wwv_flow.LF||
'   ';
wwv_flow_imp.g_varchar2_table(68) := ' END IF;   '||wwv_flow.LF||
'       '||wwv_flow.LF||
'    -- If updating old record data '||wwv_flow.LF||
'    IF UPDATING THEN   '||wwv_flow.LF||
'        IF :OLD.CREA';
wwv_flow_imp.g_varchar2_table(69) := 'TED_DATE IS NULL THEN   '||wwv_flow.LF||
'            :NEW.CREATED_DATE := SYSDATE;   '||wwv_flow.LF||
'            :NEW.CREATED_BY :=';
wwv_flow_imp.g_varchar2_table(70) := ' APEX_APPLICATION.g_user;   '||wwv_flow.LF||
'        END IF;   '||wwv_flow.LF||
'           '||wwv_flow.LF||
'        IF :OLD.UPDATED_DATE IS NULL OR ';
wwv_flow_imp.g_varchar2_table(71) := ':OLD.UPDATED_BY IS NULL OR   '||wwv_flow.LF||
'           :OLD.UPDATED_DATE != :NEW.UPDATED_DATE OR :OLD.UPDATED_BY !';
wwv_flow_imp.g_varchar2_table(72) := '= :NEW.UPDATED_BY THEN   '||wwv_flow.LF||
'            :NEW.UPDATED_DATE := SYSDATE;   '||wwv_flow.LF||
'            :NEW.UPDATED_BY :';
wwv_flow_imp.g_varchar2_table(73) := '= APEX_APPLICATION.g_user;   '||wwv_flow.LF||
'        END IF;   '||wwv_flow.LF||
'    END IF;   '||wwv_flow.LF||
'END;'||wwv_flow.LF||
'/'||wwv_flow.LF||
''||wwv_flow.LF||
''||wwv_flow.LF||
''||wwv_flow.LF||
' ';
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(14347248940437408888)
,p_install_id=>wwv_flow_imp.id(14347248144315400397)
,p_name=>'WBS Installation'
,p_sequence=>10
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_imp.varchar2_to_clob(wwv_flow_imp.g_varchar2_table)
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(14347249078126408907)
,p_script_id=>wwv_flow_imp.id(14347248940437408888)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'XTD_WBS'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(14347249269811408908)
,p_script_id=>wwv_flow_imp.id(14347248940437408888)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TABLE'
,p_object_name=>'XTD_WBS_BLOB'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(14347249420997408908)
,p_script_id=>wwv_flow_imp.id(14347248940437408888)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TRIGGER'
,p_object_name=>'XTD_WBS_BIU'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(14347249675503408908)
,p_script_id=>wwv_flow_imp.id(14347248940437408888)
,p_object_owner=>'#OWNER#'
,p_object_type=>'TRIGGER'
,p_object_name=>'XTD_WBS_BLOB_BIU'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(14347249857069408908)
,p_script_id=>wwv_flow_imp.id(14347248940437408888)
,p_object_owner=>'#OWNER#'
,p_object_type=>'SEQUENCE'
,p_object_name=>'XTD_NO_BATL'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(14347250074447408908)
,p_script_id=>wwv_flow_imp.id(14347248940437408888)
,p_object_owner=>'#OWNER#'
,p_object_type=>'SEQUENCE'
,p_object_name=>'XTD_WBS_BLOB_SEQ'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(14347250270432408908)
,p_script_id=>wwv_flow_imp.id(14347248940437408888)
,p_object_owner=>'#OWNER#'
,p_object_type=>'SEQUENCE'
,p_object_name=>'XTD_WBS_NO'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(14347250395687408908)
,p_script_id=>wwv_flow_imp.id(14347248940437408888)
,p_object_owner=>'#OWNER#'
,p_object_type=>'SEQUENCE'
,p_object_name=>'XTD_WBS_SEQ'
);
wwv_flow_imp.component_end;
end;
/
